name: Deploy to Self-Hosted Runner

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Pull Latest Docker Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pixel-art-api:latest

      - name: Stop Existing Container
        continue-on-error: true
        run: docker stop pixel-art-api

      - name: Remove Existing Container
        continue-on-error: true
        run: docker rm pixel-art-api

      - name: Run New Container
        run: docker run -d --name pixel-art-api -p 8000:80 --restart unless-stopped ${{ secrets.DOCKERHUB_USERNAME }}/pixel-art-api:latest

      - name: Clean Up Unused Docker Images
        run: docker image prune -f